version: "3.0"
services:
  api:
    image: node:lts-alpine3.14
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"
    working_dir: /app
    command: sh -c 
      "npm install &&
       cd /app/src &&
       npx sequelize-cli db:migrate &&
       npx sequelize-cli db:seed:all &&
       npm run dev
       "
    links:
      - mysql-server
    depends_on:
      - mysql-server
  front:
    image: node:lts-alpine3.14
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c 
      "npm install &&
       npm run build
       "
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint: "bash -c 'echo -e \"CREATE DATABASE IF NOT EXISTS hackaton;\" > /docker-entrypoint-initdb.d/create_hackaton_db.sql &&
                          /entrypoint.sh mysqld'"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    links:
      - api
    depends_on:
      - api
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./client:/sites/hackaton
volumes:
  mysqldata:
    driver: local